version: "3"

services:
    api:
        container_name: api
        image: php:8.1-fpm
        volumes:
            - ../:/var/www/html
    web:
        container_name: web
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ../:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
